FROM python:3.10

ARG FACEFUSION_VERSION=2.6.1
ENV GRADIO_SERVER_NAME=0.0.0.0

WORKDIR /facefusion

RUN apt-get update
RUN apt-get install curl -y
RUN apt-get install ffmpeg -y

RUN git clone https://github.com/facefusion/facefusion.git --branch ${FACEFUSION_VERSION} --single-branch .
RUN sed -i 's/= 0.80/= 1111.11/' facefusion/content_analyser.py
RUN python install.py --onnxruntime default --skip-conda
